config/routes.rb
Rails.application.routes.draw do
  resources :blockedsites
  get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blockedsite.rb
class Blockedsite < ApplicationRecord
  def display_days
    #currentTime = DateTime.now.to_time.to_i
    #(@blockedsite.duedate.to_time.to_i-currentTime)/60/60/24

    ((duedate - Time.now)/60/60/24).to_i
  end

  def display_hours
    (((duedate - Time.now)-((duedate - Time.now)/60/60/24).to_i*24*60*60)/60/60).round
  end

  def display_minutes
    (((duedate-Time.now)-(display_days*60*60*24+display_hours*60*60))/60).round
  end

  def display_seconds
    ((duedate)-((display_days.to_i*24*60*60)+(display_hours.to_i*60*60)+(display_minutes.to_i*60))).to_i.round
  end

  def setTimed
    durationtype = "Timed"
  end

  def setPermanent
    durationtype = "Permanent"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blockedsites_controller.rb
class BlockedsitesController < ApplicationController
  before_action :set_blockedsite, only: %i[ show edit update destroy ]
  helper_method :decrease, :displayDays
  # GET /blockedsites or /blockedsites.json
  def index
    @blockedsites = Blockedsite.all
    @blockedsite = Blockedsite.new
  end

  # GET /blockedsites/1 or /blockedsites/1.json
  def show
  end

  # GET /blockedsites/new
  def new
    @blockedsite = Blockedsite.new
  end

  # GET /blockedsites/1/edit
  def edit
  end

  # POST /blockedsites or /blockedsites.json

  def shortenLink(url)
    match = url.match(%r{^([^/]+://[^/]+).*})
    match ? match[1] : url
  end
  def create
    @blockedsite = Blockedsite.new(blockedsite_params)
    if @blockedsite.days == nil
      @blockedsite.days = 0
    end
    if @blockedsite.hours == nil
      @blockedsite.hours = 0
    end
    if @blockedsite.minutes == nil
      @blockedsite.minutes = 0
    end
    if @blockedsite.seconds == nil
      @blockedsite.seconds = 0
    end
    @blockedsite.duedate = (Time.now + (@blockedsite.days*24*60*60) +(@blockedsite.hours*60*60) + (@blockedsite.minutes*60) + (@blockedsite.seconds))
    url_regex = /\Ahttps?:\/\/(?:www\.)?[a-zA-Z0-9-]+(?:\.[a-zA-Z]{2,})+(?:\/[^\s]*)?\z/
    if (!@blockedsite.link.match(/\Ahttps?:\/\/(?:www\.)?[a-zA-Z0-9-]+(?:\.[a-zA-Z]{2,})+(?:\/[^\s]*)?\z/))
      respond_to do |format|
        format.html { redirect_to blockedsites_path, notice: "Please enter a valid website link" }
        format.json { render :show, status: :created, location: @blockedsite }
      end
      return
    end
    @blockedsite.link = shortenLink(@blockedsite.link)
    @blockedsite.save
    respond_to do |format|
      if @blockedsite.save
        flash[:notice] =  "Blockedsite was successfully created."
        format.html { redirect_to blockedsites_path, notice: "Blockedsite was successfully created." }
        format.json { render :show, status: :created, location: @blockedsite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blockedsite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blockedsites/1 or /blockedsites/1.json
  def update
    respond_to do |format|
      if @blockedsite.update(blockedsite_params)
        format.html { redirect_to blockedsite_url(@blockedsite), notice: "Blockedsite was successfully updated." }
        format.json { render :show, status: :ok, location: @blockedsite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blockedsite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blockedsites/1 or /blockedsites/1.json
  def destroy
    @blockedsite.destroy

    respond_to do |format|
      format.html { redirect_to blockedsites_url, notice: "Blockedsite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def displayDays
    currentTime = DateTime.now.to_time.to_i
    return (@blockedsite.duedate.to_time.to_i-currentTime)/60/60/24
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blockedsite
      @blockedsite = Blockedsite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blockedsite_params
      params.require(:blockedsite).permit(:link, :durationtype, :days, :hours, :minutes, :seconds, :duedate)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blockedsites_helper.rb
module BlockedsitesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blockedsites/_addwebsite.html.erb
<%= form_with(model: @blockedsite) do |form| %>
  <div style="display: flex; margin-bottom: 20px">
    <td><%= form.text_field :link, class: "form-link", placeholder:"Add a website URL", size: 50, style: "margin-right: 60px" %></td>

    <textarea placeholder="Add an Extension ID" style="resize: none"></textarea>
    <button style="font-size: 30px; border: none; color: #c1c1c1; background: transparent; width: 0px; height: 0px; margin-top: -5px;">+</button>
  </div>
  <h3 style="color: #666666; margin-bottom: 40px">Block Duration</h3>
  <div style="display: flex; font-size: 20px; margin-bottom: 90px">
    <div id="hide" class="form-check" style="margin-right: 65px">
      <%= form.radio_button :durationtype, @blockedsite.setPermanent, class: "form-check-input", id: "flexRadioDefault1" %>
      <label class="form-check-label" for="flexRadioDefault1">
        Permanent
      </label>
    </div>
    <div id="show" class="form-check">
      <%= form.radio_button :durationtype, @blockedsite.setTimed, :checked => true, class: "form-check-input", id: "flexRadioDefault2"%>
      <label class="form-check-label" for="flexRadioDefault2">
        Timer
      </label>
    </div>
    <div id="timer-settings" style=" margin-left: 30px;margin-top: -11px">
      <td><%= form.number_field :days, min:0, max:999, placeholder: "0", class: "size"%></td>
      <b style="font-size: 30px; margin-top: -6px">:</b>
      <td><%= form.number_field :hours, min:0, max:24, placeholder: "0", class: "size"%></td>
      <b style="font-size: 30px; margin-top: -6px">:</b>
      <td><%= form.number_field :minutes, min:0, max:60, placeholder: "0", class: "size"%></td>
      <b style="font-size: 30px; margin-top: -6px">:</b>
      <td><%= form.number_field :seconds, min:0, max:60, placeholder: "0", class: "size"%></td>
    </div>
    <div onclick="sendData()">
    <%= form.submit :+, style: "font-size: 30px; border: none; color: #c1c1c1; background: transparent; margin-top: -10px;" %>
    </div>
  </div>
<% end %>

app/views/blockedsites/_blockedsite.html.erb
<div id="<%= dom_id blockedsite %>">
  <p>
    <strong>Link:</strong>
    <%= blockedsite.link %>
  </p>

  <p>
    <strong>Durationtype:</strong>
    <%= blockedsite.durationtype %>
  </p>

  <p>
    <strong>Days:</strong>
    <%= blockedsite.days %>
  </p>

  <p>
    <strong>Hours:</strong>
    <%= blockedsite.hours %>
  </p>

  <p>
    <strong>Minutes:</strong>
    <%= blockedsite.minutes %>
  </p>

  <p>
    <strong>Seconds:</strong>
    <%= blockedsite.seconds %>
  </p>

  <p>
    <strong>Duedate:</strong>
    <%= blockedsite.duedate %>
  </p>

</div>

app/views/blockedsites/_form.html.erb
<%= form_with(model: blockedsite) do |form| %>
  <% if blockedsite.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blockedsite.errors.count, "error") %> prohibited this blockedsite from being saved:</h2>

      <ul>
        <% blockedsite.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.label :durationtype, style: "display: block" %>
    <%= form.text_field :durationtype %>
  </div>

  <div>
    <%= form.label :days, style: "display: block" %>
    <%= form.number_field :days, min:0%>
  </div>

  <div>
    <%= form.label :hours, style: "display: block" %>
    <%= form.number_field :hours, max:24, min:0%>
  </div>

  <div>
    <%= form.label :minutes, style: "display: block" %>
    <%= form.number_field :minutes, max: 60, min: 0 %>
  </div>

  <div>
    <%= form.label :seconds, style: "display: block" %>
    <%= form.number_field :seconds, max: 60, min: 0 %>
  </div>

  <div>
    <%= form.label :duedate, style: "display: block" %>
    <%= form.date_field :duedate %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blockedsites/edit.html.erb
<h1>Editing blockedsite</h1>

<%= render "form", blockedsite: @blockedsite %>

<br>

<div>
  <%= link_to "Show this blockedsite", @blockedsite %> |
  <%= link_to "Back to blockedsites", blockedsites_path %>
</div>

app/views/blockedsites/index.html.erb
<% if notice %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">X</button>
  </div>
<% end %>
<body>
<h1 style="font-weight: bold; color: #666666">Add a website</h1>
<%= render 'addwebsite' %>
<div>
  <hr style="margin-bottom: 35px"/>



  <h2 style="color: #666666">Blockedsites</h2>
<div id="blockedsites">
  <table class="table table-striped table-dark">
    <thead>
    <tr>
      <th scope="col">Link</th>
      <th scope="col">Type</th>
      <th scope="col">Days</th>
      <th scope="col">Hours</th>
      <th scope="col">Minutes</th>
      <th scope="col">Seconds</th>
    </tr>
    </thead>

    <tbody  id="timerTable" >
    <div style="display: none"><%@counter = 0 %></div>
    <% @blockedsites.each do |blockedsite| %>

    <tr>
      <td><%=blockedsite.link %></td>
      <td><%=blockedsite.durationtype %></td>
      <td id="days <%=@counter%>"></td>
      <td id="hours <%=@counter%>"></td>
      <td id="minutes <%=@counter%>"></td>
      <td id="seconds <%=@counter%>"></td>
      <script type="text/javascript">
          decrementDays(<%=@counter%>, "<%=blockedsite.duedate.to_time.to_s%>");
          decrementHours(<%=@counter%>, "<%=blockedsite.duedate.to_time.to_s%>");
          decrementMinutes(<%=@counter%>, "<%=blockedsite.duedate.to_time.to_s%>");
          decrementSeconds(<%=@counter%>, "<%=blockedsite.duedate.to_time.to_s%>");
      </script>
      <td><%= link_to "Show this blockedsite", blockedsite, class: "btn btn-secondary" %></td>
      <td><%= button_to "Remove Timer", blockedsite_path(blockedsite), method: :delete, class: "btn btn-secondary", id: ("delete "+@counter.to_s) %></td>
      <div style="display: none"><%@counter +=1 %></div>
    <% end %>
    </tr>
    <tr>
      <%= form_with(model: @blockedsite) do |form| %>
        <% if @blockedsite.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(@blockedsite.errors.count, "error") %> prohibited this blockedsite from being saved:</h2>

            <ul>
              <% @blockedsite.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

      <% end %>
    </tr>
    </tbody>
  </table>
</div>

  <script type="text/javascript">

  </script>


<%= link_to "New blockedsite", new_blockedsite_path %>
</div>
</body>

app/views/blockedsites/new.html.erb
<h1>New blockedsite</h1>

<%= render "form", blockedsite: @blockedsite %>

<br>

<div>
  <%= link_to "Back to blockedsites", blockedsites_path %>
</div>

app/views/blockedsites/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blockedsite %>

<div>
  <%= link_to "Edit this blockedsite", edit_blockedsite_path(@blockedsite) %> |
  <%= link_to "Back to blockedsites", blockedsites_path %>

  <%= button_to "Destroy this blockedsite", @blockedsite, method: :delete %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Home', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Blocked Sites', blockedsites_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', home_about_path, class: 'nav-link' %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<button class="test" onclick="SayHI()">sayhi</button>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebSiteBlocker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body style="background: #D9DDDC">
    <div>
    <%= render '/home/header' %>
    </div>
    <%= yield %>
  </body>
</html>